# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

build: off

environment:
  GITHUB_ACCESS_TOKEN:
    secure: 2GfPxgGBKuqQGfnTEuYxqMbS97ohi0o5fxlc70ihcv5ey6FJhVhWCpOrPxlekrbO

# appveyor.yml
install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
