# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

build: off

environment:
  GITHUB_ACCESS_TOKEN:
    secure: 5drFLFNj3hmrLLWt385zNdAly6bfTE3nDqLHpmFWfX7XtEVISPek5fwspic32s9i

# appveyor.yml
install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

notifications:
  - provider: Slack
    incoming_webhook:
      secure: zUujuzaZFqpFndOFkoIMkXMFTniWWi0ZtR58PN63c7+KijEb2IMFDPvSMPeIpx/nWQTOLxA/dxX0fSyBjY33TnYtujPTO/bNzER3cppwyX0=
